### ISSUE TITLE
Repeated connected/disconnected message

### ISSUE THREAD

**Issue by marcetcheverry** [ptrm/prettysimple-adiummsgstyle#3]
Can you update this theme so the repeated you have connected/disconnect messages are coalesced?

See https://trac.adium.im/ticket/15600 (last comment)

**Comment by ptrm** [comment]
Hello,

Sorry for a late reply. I actually agree with the [last comment in the ticket](https://trac.adium.im/ticket/15600#comment:9), and would prefer to leave status messages uncoalesced.

However, you might want to add coalescing yourself. Just download this repo as zip, unpack it, right click the theme file and browse the package contents, and edit Status.html. Then install the style as usual.
